#include "woodland/acorn/elastostatics_integrals.hpp"

namespace woodland {
namespace acorn {

int get_triquad_order (const Real L, const Real dist, const Real tol) {
#if 0
  const int fac = 1;
  return (dist <  3*L*fac ? 20 :
          dist <  4*L*fac ? 12 :
          dist <  6*L*fac ?  8 :
          dist < 16*L*fac ?  4 :
          dist < 24*L*fac ?  2 :
          1);
#else
  // Generated by ./acorn/testmain study_triquad
  if (tol <= 1.0e-14) {
    return (dist <    3.2*L ? 20 :
            dist <    9.2*L ? 12 :
            dist <   21.5*L ?  8 :
            dist <   85.9*L ?  6 :
            dist < 1409.9*L ?  4 :
            2);
  } else if (tol <= 1.0e-12) {
    return (dist <    2.2*L ? 20 :
            dist <    5.4*L ? 12 :
            dist <   11.7*L ?  8 :
            dist <   40.4*L ?  6 :
            dist <  438.0*L ?  4 :
            2);
  } else if (tol <= 1.0e-10) {
    return (dist <    1.5*L ? 20 :
            dist <    3.2*L ? 12 :
            dist <    6.2*L ?  8 :
            dist <   18.2*L ?  6 :
            dist <  140.2*L ?  4 :
            2);
  } else if (tol <= 1.0e-08) {
    return (dist <    0.9*L ? 20 :
            dist <    1.9*L ? 12 :
            dist <    3.3*L ?  8 :
            dist <    8.0*L ?  6 :
            dist <   43.2*L ?  4 :
            dist < 4114.8*L ?  2 :
            1);
  } else {
    return (dist <    0.8*L ? 20 :
            dist <    1.1*L ? 12 :
            dist <    1.6*L ?  8 :
            dist <    3.4*L ?  6 :
            dist <   13.4*L ?  4 :
            dist <  410.4*L ?  2 :
            1);
  }
#endif
}

} // namespace acorn
} // namespace woodland
